### PR TITLE
react to DependencyContext changes

### PR DESCRIPTION
**Pull request by analogrelay**
/cc @piotrpMSFT @pakrym @pranavkm

### CODE REVIEW

**Comment by pakrym** [comment]
Looks fine, :shipit:

**Comment by analogrelay** [comment]
@livarcocc , @pakrym  says you know how to get this merged and built and stuff. Let me know if I messed anything up. I had to hack up some things to get it to build...

**Comment by pranavkm** [comment]
:shipit:

**Comment by pranavkm** [comment]
@livarcocc. how long until this change ends up on https://www.myget.org/F/coreclr-xunit/api/v3/index.json ?

**Comment by livarcocc** [comment]
I believe it is already there. Package 1.0.0-dev-121895-16.

**Comment by pranavkm** [comment]
Great!

**Pull request merged**
